<a href="https://colab.research.google.com/github/noallynoclan/colab/blob/master/pytorch_tutorials_01_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import torch
from pprint import pprint

In [17]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, 
                         device=device, requires_grad=True)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
torch.Size([2, 3])


In [43]:
x = torch.empty(size=(3, 3))
print(x)
x = torch.zeros(3, 3)
print(x)
x = torch.rand(3, 3) # uniform
print(x)
x = torch.arange(0, 5, 1)
print(x)
x = torch.linspace(0.1, 1, 10)
print(x)
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(x)
x = torch.empty(size=(1, 5)).uniform_(0, 1)
print(x)
x = torch.arange(5)
print(x.bool())
print(x.short())
print(x.long())
print(x.half())

tensor([[2.3975e-35, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44],
        [1.4153e-43, 1.5274e-43, 1.5695e-43]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9728, 0.7616, 0.8912],
        [0.4153, 0.5059, 0.6987],
        [0.1141, 0.9971, 0.2818]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[0.5049, 1.7506, 0.2998, 1.0119, 0.6218]])
tensor([[0.6645, 0.5118, 0.9764, 0.0969, 0.5047]])
tensor([False,  True,  True,  True,  True])
tensor([0, 1, 2, 3, 4], dtype=torch.int16)
tensor([0, 1, 2, 3, 4])
tensor([0., 1., 2., 3., 4.], dtype=torch.float16)


In [47]:
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()

In [70]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)
z2 = torch.add(x, y)
print(z2)
z = x + y
print(z)
z = torch.true_divide(x, y)
print(z)
t = torch.zeros(3)
t.add_(x)
print(t)
t += x 
print(t)
z = x.pow(2)
print(z)
z = x ** 2
print(z)
z = x > 0
print(z)
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)
print(x3)
x3 = x1.mm(x2)
print(x3)
x3 = x1 @ x2
print(x3)
matrix_exp = torch.rand(2, 2)
print(matrix_exp)
print(matrix_exp.matrix_power(3))

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])
tensor([0.1111, 0.2500, 0.4286])
tensor([1., 2., 3.])
tensor([2., 4., 6.])
tensor([1, 4, 9])
tensor([1, 4, 9])
tensor([True, True, True])
tensor([[1.1617, 1.1882, 2.0347],
        [0.9010, 1.4881, 0.9598]])
tensor([[1.1617, 1.1882, 2.0347],
        [0.9010, 1.4881, 0.9598]])
tensor([[1.1617, 1.1882, 2.0347],
        [0.9010, 1.4881, 0.9598]])
tensor([[0.6574, 0.3006],
        [0.8776, 0.4123]])
tensor([[0.7398, 0.3418],
        [0.9978, 0.4610]])


In [74]:
batch = 4
n = 2
m = 3
p = 4
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm)

tensor([[[0.9140, 0.2981, 0.8823, 0.9114],
         [0.2826, 0.0965, 0.2009, 0.2939]],

        [[0.1572, 0.0411, 0.2134, 0.1308],
         [0.9829, 0.2178, 1.1708, 0.6199]],

        [[0.9505, 1.2537, 0.8303, 1.1831],
         [1.4023, 1.2313, 0.2331, 1.1223]],

        [[0.6953, 0.2808, 0.4020, 0.9245],
         [0.1739, 0.6117, 0.5824, 0.6487]]])


In [75]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))
z = x1 - x2
print(z)

tensor([[ 0.0749, -0.1287,  0.0557,  0.0449, -0.0778],
        [ 0.1528, -0.3274, -0.1720,  0.0186,  0.4571],
        [-0.2495, -0.5509, -0.5167, -0.5077, -0.4197],
        [-0.1385,  0.2540, -0.6358, -0.4702,  0.2433],
        [ 0.2158, -0.3369, -0.0462, -0.5296, -0.4331]])


In [77]:
torch.sum(z, dim=0)

tensor([ 0.0556, -1.0899, -1.3150, -1.4440, -0.2302])

In [81]:
values, indices = torch.max(z, dim=1)
print(values, indices)
indices = torch.argmax(z, dim=1)
print(indices)

tensor([ 0.0749,  0.4571, -0.2495,  0.2540,  0.2158]) tensor([0, 4, 0, 1, 0])
tensor([0, 4, 0, 1, 0])


In [88]:
z = torch.tensor([[1, 2], [3, 4]])
print(z)
z.clamp_(min=2, max=3)
print(z)

tensor([[1, 2],
        [3, 4]])
tensor([[2, 2],
        [3, 3]])


In [89]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
x[0]

tensor([0.6484, 0.8172, 0.8313, 0.5613, 0.1993, 0.1976, 0.7421, 0.6054, 0.0252,
        0.4054, 0.7335, 0.4869, 0.6675, 0.4550, 0.9368, 0.5102, 0.3673, 0.1955,
        0.5202, 0.5679, 0.2698, 0.3099, 0.1142, 0.6142, 0.4619])

In [90]:
x = torch.arange(9)

In [91]:
x.view(3, 3)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
z = torch.cat((x1, x2), dim=0)
print(z.shape)
print(z.view(-1))

torch.Size([4, 5])
tensor([0.8397, 0.0414, 0.4633, 0.6976, 0.4498, 0.0232, 0.4982, 0.1982, 0.8591,
        0.3675, 0.9605, 0.3100, 0.1045, 0.7899, 0.6537, 0.2669, 0.8546, 0.5912,
        0.7422, 0.0264])
